// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as React$1 from "@remix-run/react";

function Nav(Props) {
  return React.createElement("div", {
              className: "w-full"
            }, React.createElement("nav", {
                  className: "max-w-5xl p-5 flex items-center justify-between m-auto text-white"
                }, React.createElement(React$1.Link, {
                      prefetch: "none",
                      to: "/",
                      children: React.createElement("span", {
                            className: "font-bold text-3xl daimonion"
                          }, "Lair Game")
                    })));
}

var make = Nav;

export {
  make ,
  
}
/* react Not a pure module */
